POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "name": "JJ",
    "email": "jailton.junior94@outlook.com",
    "password": "123456"
}

###
POST http://localhost:8000/token HTTP/1.1
Content-Type: application/json

{
    "email": "jailton.junior94@outlook.com",
    "password": "123456"
}